/**
 * Tên phường/xã TP.HCM (sau sáp nhập) — dùng đối chiếu trong chuỗi `address`
 * khi không có tiền tố "Phường" / "P.".
 */
export const HCMC_WARD_NAMES = [
  'Sài Gòn',
  'Tân Định',
  'Bến Thành',
  'Cầu Ông Lãnh',
  'Bàn Cờ',
  'Xuân Hòa',
  'Nhiêu Lộc',
  'Xóm Chiếu',
  'Khánh Hội',
  'Vĩnh Hội',
  'Chợ Quán',
  'An Đông',
  'Chợ Lớn',
  'Bình Tây',
  'Bình Tiên',
  'Bình Phú',
  'Phú Lâm',
  'Tân Thuận',
  'Phú Thuận',
  'Tân Mỹ',
  'Tân Hưng',
  'Chánh Hưng',
  'Phú Định',
  'Bình Đông',
  'Diên Hồng',
  'Vườn Lài',
  'Hòa Hưng',
  'Minh Phụng',
  'Bình Thới',
  'Hòa Bình',
  'Phú Thọ',
  'Đông Hưng Thuận',
  'Trung Mỹ Tây',
  'Tân Thới Hiệp',
  'Thới An',
  'An Phú Đông',
  'An Lạc',
  'Bình Tân',
  'Tân Tạo',
  'Bình Trị Đông',
  'Bình Hưng Hòa',
  'Gia Định',
  'Bình Thạnh',
  'Bình Lợi Trung',
  'Thạnh Mỹ Tây',
  'Bình Quới',
  'Hạnh Thông',
  'An Nhơn',
  'Gò Vấp',
  'An Hội Đông',
  'Thông Tây Hội',
  'An Hội Tây',
  'Đức Nhuận',
  'Cầu Kiệu',
  'Phú Nhuận',
  'Tân Sơn Hòa',
  'Tân Sơn Nhất',
  'Tân Hòa',
  'Bảy Hiền',
  'Tân Bình',
  'Tân Sơn',
  'Tây Thạnh',
  'Tân Sơn Nhì',
  'Phú Thọ Hòa',
  'Tân Phú',
  'Phú Thạnh',
  'Hiệp Bình',
  'Thủ Đức',
  'Tam Bình',
  'Linh Xuân',
  'Tăng Nhơn Phú',
  'Long Bình',
  'Long Phước',
  'Long Trường',
  'Cát Lái',
  'Bình Trưng',
  'Phước Long',
  'An Khánh',
  'Đông Hòa',
  'Dĩ An',
  'Tân Đông Hiệp',
  'An Phú',
  'Bình Hòa',
  'Lái Thiêu',
  'Thuận An',
  'Thuận Giao',
  'Thủ Dầu Một',
  'Phú Lợi',
  'Chánh Hiệp',
  'Bình Dương',
  'Hòa Lợi',
  'Phú An',
  'Tây Nam',
  'Long Nguyên',
  'Bến Cát',
  'Chánh Phú Hòa',
  'Vĩnh Tân',
  'Bình Cơ',
  'Tân Uyên',
  'Tân Hiệp',
  'Tân Khánh',
  'Vũng Tàu',
  'Tam Thắng',
  'Rạch Dừa',
  'Phước Thắng',
  'Long Hương',
  'Bà Rịa',
  'Tam Long',
  'Tân Hải',
  'Tân Phước',
  'Phú Mỹ',
] as const;

/** Khớp tên dài trước (VD: "Tân Sơn Nhất" trước "Tân Sơn"). */
export const HCMC_WARD_NAMES_BY_LENGTH = [...HCMC_WARD_NAMES].sort((a, b) => b.length - a.length);
